# Generated by Django 4.2.7 on 2023-11-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_comments_user_id_alter_likes_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='bio',
            field=models.CharField(max_length=1500, null=True),
        ),
    ]
