# Generated by Django 4.2.7 on 2023-11-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_student_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubForums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=100)),
            ],
        ),
    ]
