# Generated by Django 4.2.7 on 2023-11-09 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_subforum_rename_comments_comment_rename_likes_like_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='post_sub_name',
        ),
    ]
