# Generated by Django 4.2.7 on 2023-11-09 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_comment_post_id_remove_posts_com_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='User_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student'),
        ),
    ]
