# Generated by Django 4.2.7 on 2023-11-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_posts_comments_comment_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='bio',
            field=models.TextField(default='Please add bio in settings'),
        ),
    ]
