# Generated by Django 4.2.7 on 2023-11-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_student_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='bio',
            field=models.TextField(blank=True, default='Please add bio in settings'),
        ),
    ]
