# Generated by Django 4.2.7 on 2023-11-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_student_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='count_likes',
            field=models.IntegerField(blank=True),
        ),
    ]
