# Generated by Django 4.2.7 on 2023-11-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_posts_count_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='com_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='count_likes',
            field=models.IntegerField(default=0),
        ),
    ]
