# Generated by Django 4.2.7 on 2023-11-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_posts_post_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='com_contents',
            field=models.TextField(max_length=500),
        ),
    ]
