# Generated by Django 4.2.7 on 2023-11-07 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('Comment_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('count_likes', models.IntegerField()),
                ('pin', models.BooleanField(default=False)),
                ('reported', models.BooleanField(default=False)),
                ('com_contents', models.CharField(max_length=500)),
                ('com_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('User_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('email_address', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('user_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=1500)),
                ('banned', models.BooleanField(default=False)),
                ('avatar', models.FileField(upload_to='')),
                ('reported', models.BooleanField(default=False)),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('Post_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('post_name', models.CharField(max_length=250)),
                ('post_sub_name', models.CharField(max_length=250)),
                ('contents', models.CharField(max_length=1500)),
                ('count_likes', models.IntegerField()),
                ('locked', models.BooleanField(default=False)),
                ('pin', models.BooleanField(default=False)),
                ('reported', models.BooleanField(default=False)),
                ('post_date', models.DateTimeField()),
                ('com_count', models.IntegerField()),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Special_P', models.BooleanField(default=True)),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('Like_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('likes', models.IntegerField()),
                ('Comment_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.comments')),
                ('Post_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.posts')),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='Post_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.posts'),
        ),
        migrations.AddField(
            model_name='comments',
            name='User_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
    ]
