# Generated by Django 4.2.7 on 2023-11-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_subforums_posts_subforum_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='Comment_ID',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='Like_ID',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='Post_ID',
        ),
        migrations.AddField(
            model_name='comments',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='likes',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
