# Generated by Django 4.2.7 on 2023-11-10 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_comment_com_date_alter_comment_count_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_name',
            field=models.TextField(max_length=400),
        ),
    ]
